server:
  error:
    include-message: always
    include-binding-errors: always
  port: 8081

spring:
  datasource:
    password: password
    url: jdbc:mysql://localhost:3306/gateway
    username: root
    initialization-mode: always
  jpa:
    hibernate:
#      ddl-auto: create
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
#        format_sql: true
        enable_lazy_load_no_trans: true
        defer-datasource-initialization: true
#    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: thiensudanduong12@gmail.com
    password: gggcnulmltoibrwr
    
#    host: localhost
#    port: 1025
#    username: hello
#    password: hellp
    
#    host: smtp.mail.yahoo.com
#    port: 465
 #   username: thuanntd108@yahoo.com
#    password: qejnrixjquuwqepx

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
#          connectiontimeout: 5000
#          timeout: 3000
#          writetimeout: 5000
